language: node_js
node_js:
- '10'
branches:
  only:
    - master
    - deployment
deploy:
  provider: heroku
  api_key:
    secure: rJ0EmR/s3cPL3k9BN9JuIs+b/Unpwgbo5/PepprAdtel6XROJr7HVnTUgyj6vtimk06to7AXFwrcSGrfEBiUBCSdHSWjDmCl1BXNZ26sdFkLbdzedgVVZKJoH0jPbpz7pG1WII4NOxS+mXF/GiTQFjDOCLO2S1qecW+R8PVtzLi5htFSLnJ/CPv0qaB02ywfNu4QdYeNkfecdO6ScAeRSXNLkpoc8tALqj4+CdhXHdlMDnc5L45GqG0h2wUDZ3VBA5LgKrTYryRkKsCDbSmDhwnBS1AwQmPIIMZpSm4GfO8SxLd83qs1OFODER4YZ9RkETGV0enJSg/AyFN0aW1NqsWhAD3WN1/KTZPaQb6qWGAGGfqWKs1xkC3k1K9GYIra8KqmJmEHTzlU3TKfTacMpEnsZoK+IKAN2HJWqAtASjIKI/ZBAzQq9tOEHH9tCZ4fuw2raNATMbucrg/KMNhfaxw8ggprSD4g/ilCorw1viKmCaZqEHitRevn9cJz3HC3xVRHfCQh+yAQnm8lQwbQIzLEyfOYSkxEuZoAwRgUassc0aXpaj7CxpzLZ2OBEXQumuVN6VERL3QlLgDYCztPD53K9VWNL93mePXam5FFPNiAVZ+W4VHalw88aAnMz2nQdOFQ/VjQunRi5NBT6bPRr+3CuFXo0ZgCoHcI7vDzzR8=
